name: scanfold_moneypoint
description: A new Flutter fintech project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9 # ✅ Downgraded for compatibility with image_cropper <5.0.0

  # State Management
  provider: ^6.1.1

  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Formatting
  intl: ^0.19.0

  # Animations
  animated_text_kit: ^4.2.2

  # Charts
  fl_chart: ^0.66.2

  # ✅ Firebase Core & Auth
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5
  google_sign_in: ^6.2.1

  # ✅ Biometrics
  local_auth: ^2.1.8

  # ✅ Image Picker & Cropper
  image_picker: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.jpg
    - assets/images/image2.jpg
    - assets/images/image6.jpg
    - assets/images/login_bg.jpg
    - assets/images/logo1.png
    - assets/images/white.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
